<?php
/**
 * NewsstreamApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zoo iPhone & Android APP
 *
 * OpenApi Definition for Zoo iPhone & Android APP.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * NewsstreamApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NewsstreamApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getNewsstreamPool
     *
     * Newsstream
     *
     * @param  int $page Pagination Page ID, by default page 1 is returned. Pagination starts at 1 (optional)
     * @param  int $per_page The number of items which should be returned per page, max is 100. By default its 25 items (optional)
     * @param  string $sort Certain content pools can be sorted, if sorting is enabled its possible to define &#x60;?sort&#x3D;id&#x60; ASC (A-Z or 1-9) or for opposite sort &#x60;?sort&#x3D;-id&#x60; DESC (Z-A or 9-1). Sorting multiple items can be achieved by seperating by comma &#x60;?sort&#x3D;created_at,updated_at&#x60; (optional)
     * @param  object $filter Allows you to pass filtering options any attribute. &#x60;?filter[id]&#x3D;123&#x60; or &#x60;?filter[author][like]&#x3D;John&#x60;. Example of accessing nested array values &#x60;?filter[tags.alias]&#x3D;food&#x60; (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\NewsstreamPool[]
     */
    public function getNewsstreamPool($page = null, $per_page = null, $sort = null, $filter = null)
    {
        list($response) = $this->getNewsstreamPoolWithHttpInfo($page, $per_page, $sort, $filter);
        return $response;
    }

    /**
     * Operation getNewsstreamPoolWithHttpInfo
     *
     * Newsstream
     *
     * @param  int $page Pagination Page ID, by default page 1 is returned. Pagination starts at 1 (optional)
     * @param  int $per_page The number of items which should be returned per page, max is 100. By default its 25 items (optional)
     * @param  string $sort Certain content pools can be sorted, if sorting is enabled its possible to define &#x60;?sort&#x3D;id&#x60; ASC (A-Z or 1-9) or for opposite sort &#x60;?sort&#x3D;-id&#x60; DESC (Z-A or 9-1). Sorting multiple items can be achieved by seperating by comma &#x60;?sort&#x3D;created_at,updated_at&#x60; (optional)
     * @param  object $filter Allows you to pass filtering options any attribute. &#x60;?filter[id]&#x3D;123&#x60; or &#x60;?filter[author][like]&#x3D;John&#x60;. Example of accessing nested array values &#x60;?filter[tags.alias]&#x3D;food&#x60; (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\NewsstreamPool[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getNewsstreamPoolWithHttpInfo($page = null, $per_page = null, $sort = null, $filter = null)
    {
        $request = $this->getNewsstreamPoolRequest($page, $per_page, $sort, $filter);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\NewsstreamPool[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\NewsstreamPool[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\NewsstreamPool[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\NewsstreamPool[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getNewsstreamPoolAsync
     *
     * Newsstream
     *
     * @param  int $page Pagination Page ID, by default page 1 is returned. Pagination starts at 1 (optional)
     * @param  int $per_page The number of items which should be returned per page, max is 100. By default its 25 items (optional)
     * @param  string $sort Certain content pools can be sorted, if sorting is enabled its possible to define &#x60;?sort&#x3D;id&#x60; ASC (A-Z or 1-9) or for opposite sort &#x60;?sort&#x3D;-id&#x60; DESC (Z-A or 9-1). Sorting multiple items can be achieved by seperating by comma &#x60;?sort&#x3D;created_at,updated_at&#x60; (optional)
     * @param  object $filter Allows you to pass filtering options any attribute. &#x60;?filter[id]&#x3D;123&#x60; or &#x60;?filter[author][like]&#x3D;John&#x60;. Example of accessing nested array values &#x60;?filter[tags.alias]&#x3D;food&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNewsstreamPoolAsync($page = null, $per_page = null, $sort = null, $filter = null)
    {
        return $this->getNewsstreamPoolAsyncWithHttpInfo($page, $per_page, $sort, $filter)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNewsstreamPoolAsyncWithHttpInfo
     *
     * Newsstream
     *
     * @param  int $page Pagination Page ID, by default page 1 is returned. Pagination starts at 1 (optional)
     * @param  int $per_page The number of items which should be returned per page, max is 100. By default its 25 items (optional)
     * @param  string $sort Certain content pools can be sorted, if sorting is enabled its possible to define &#x60;?sort&#x3D;id&#x60; ASC (A-Z or 1-9) or for opposite sort &#x60;?sort&#x3D;-id&#x60; DESC (Z-A or 9-1). Sorting multiple items can be achieved by seperating by comma &#x60;?sort&#x3D;created_at,updated_at&#x60; (optional)
     * @param  object $filter Allows you to pass filtering options any attribute. &#x60;?filter[id]&#x3D;123&#x60; or &#x60;?filter[author][like]&#x3D;John&#x60;. Example of accessing nested array values &#x60;?filter[tags.alias]&#x3D;food&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNewsstreamPoolAsyncWithHttpInfo($page = null, $per_page = null, $sort = null, $filter = null)
    {
        $returnType = '\OpenAPI\Client\Model\NewsstreamPool[]';
        $request = $this->getNewsstreamPoolRequest($page, $per_page, $sort, $filter);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNewsstreamPool'
     *
     * @param  int $page Pagination Page ID, by default page 1 is returned. Pagination starts at 1 (optional)
     * @param  int $per_page The number of items which should be returned per page, max is 100. By default its 25 items (optional)
     * @param  string $sort Certain content pools can be sorted, if sorting is enabled its possible to define &#x60;?sort&#x3D;id&#x60; ASC (A-Z or 1-9) or for opposite sort &#x60;?sort&#x3D;-id&#x60; DESC (Z-A or 9-1). Sorting multiple items can be achieved by seperating by comma &#x60;?sort&#x3D;created_at,updated_at&#x60; (optional)
     * @param  object $filter Allows you to pass filtering options any attribute. &#x60;?filter[id]&#x3D;123&#x60; or &#x60;?filter[author][like]&#x3D;John&#x60;. Example of accessing nested array values &#x60;?filter[tags.alias]&#x3D;food&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNewsstreamPoolRequest($page = null, $per_page = null, $sort = null, $filter = null)
    {

        $resourcePath = '/pools/179';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }
        // query params
        if ($per_page !== null) {
            if('form' === 'form' && is_array($per_page)) {
                foreach($per_page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['per-page'] = $per_page;
            }
        }
        // query params
        if ($sort !== null) {
            if('form' === 'form' && is_array($sort)) {
                foreach($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sort'] = $sort;
            }
        }
        // query params
        if ($filter !== null) {
            if('deepObject' === 'deepObject' && is_array($filter)) {
                foreach($filter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['filter'] = $filter;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer (AuthToken) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation viewNewsstreamPool
     *
     * Newsstream View
     *
     * @param  int $id The row id to view (required)
     * @param  string $fields In order to reduce the http transfer content size, its possible to define &#x60;?fields&#x3D;id,firstname,lasstname&#x60; which are part of the response. Any other field will not be returned, except of metric, which is always present. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\NewsstreamPool
     */
    public function viewNewsstreamPool($id, $fields = null)
    {
        list($response) = $this->viewNewsstreamPoolWithHttpInfo($id, $fields);
        return $response;
    }

    /**
     * Operation viewNewsstreamPoolWithHttpInfo
     *
     * Newsstream View
     *
     * @param  int $id The row id to view (required)
     * @param  string $fields In order to reduce the http transfer content size, its possible to define &#x60;?fields&#x3D;id,firstname,lasstname&#x60; which are part of the response. Any other field will not be returned, except of metric, which is always present. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\NewsstreamPool, HTTP status code, HTTP response headers (array of strings)
     */
    public function viewNewsstreamPoolWithHttpInfo($id, $fields = null)
    {
        $request = $this->viewNewsstreamPoolRequest($id, $fields);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\NewsstreamPool' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\NewsstreamPool', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\NewsstreamPool';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\NewsstreamPool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation viewNewsstreamPoolAsync
     *
     * Newsstream View
     *
     * @param  int $id The row id to view (required)
     * @param  string $fields In order to reduce the http transfer content size, its possible to define &#x60;?fields&#x3D;id,firstname,lasstname&#x60; which are part of the response. Any other field will not be returned, except of metric, which is always present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewNewsstreamPoolAsync($id, $fields = null)
    {
        return $this->viewNewsstreamPoolAsyncWithHttpInfo($id, $fields)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation viewNewsstreamPoolAsyncWithHttpInfo
     *
     * Newsstream View
     *
     * @param  int $id The row id to view (required)
     * @param  string $fields In order to reduce the http transfer content size, its possible to define &#x60;?fields&#x3D;id,firstname,lasstname&#x60; which are part of the response. Any other field will not be returned, except of metric, which is always present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function viewNewsstreamPoolAsyncWithHttpInfo($id, $fields = null)
    {
        $returnType = '\OpenAPI\Client\Model\NewsstreamPool';
        $request = $this->viewNewsstreamPoolRequest($id, $fields);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'viewNewsstreamPool'
     *
     * @param  int $id The row id to view (required)
     * @param  string $fields In order to reduce the http transfer content size, its possible to define &#x60;?fields&#x3D;id,firstname,lasstname&#x60; which are part of the response. Any other field will not be returned, except of metric, which is always present. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function viewNewsstreamPoolRequest($id, $fields = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling viewNewsstreamPool'
            );
        }

        $resourcePath = '/pools/179/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($fields !== null) {
            if('form' === 'form' && is_array($fields)) {
                foreach($fields as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['fields'] = $fields;
            }
        }


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer (AuthToken) authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
